<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Psr\\EventDispatcher\\' => array($vendorDir . '/psr/event-dispatcher/src'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'League\\Event\\' => array($vendorDir . '/league/event/src'),
    'League\\Container\\' => array($vendorDir . '/league/container/src'),
    'Breeze\\' => array($baseDir . '/Sources/Breeze'),
);
