document.addEventListener('DOMContentLoaded', () => {
	'use strict';
	const quotes = [
		"HOW DO YOU FEEL<br>ABOUT YOUR CREATION?<br>(IT WILL NOT HEAR.)",
		"MY HEARTS GO OUT TO ALL YOU SINNERS!",
		"WHO KEEPS SPINNING THE WORLD AROUND?",
		"A BEAUTY IS JOYING IN MY HEART!", 
		"The air crackles with freedom.",
		"Halt, clowns! This bike is fueled by victory!!!",
		"Hohoho!!! I'm the bad guy!",
		"Oh! You make my feelings do wheelies! Sweet wheelys",
		"This bike is fueled by EVIL! ...and friendship!",
		"It was a LEGEND of HOPE. It was a LEGEND of DREAMS.",
		"It was a LEGEND of LIGHT. It was a LEGEND of DARK.",
		"Is that a cut on your face, or part of your eye?",
		"The gash weaves down as if you cry.",
		"The pain itself is reason why.",
		"... 2 minutes in jail and you've already resorted to eating moss.",
		"Such is the way of the worm...",
		"These <span style=\"color:yellow;\">birds</span> are <span style=\"color:yellow;\">Pissing</span> me off...",
		"I'm the original &nbsp; &nbsp; &nbsp; &nbsp; <span style=\"color:yellow;\">Starwalker</span> ",
		"Bunnies are the sequel to frogs.",
		"Thanks for inviting me! This trash can's really great!",
		"I have high hopes for the new King. He's already mandated a 400-percent increase in salsa production.",
		"I shall giveth thou a plate of Worms for thou silence.",
		"I love reading books. Especially the books upstairs. You should really. Read them!",
		"I love reading books. Especially... The books.",
		"Whew! I sure love PANCAKE!",
		"You can't read these symbols...Or maybe it's the handwriting.",
		"Not too important, not too unimportant.",
		"What Egg?",
		"Suddenly, your body seizes up. What are you looking at?",
		"It's a beautiful day outside.",
		"\"Try your best, Astral Wolf! Even in your darkest hour...!\"",
		"(Please surf the web responsibly.) (In fact, maybe don't do it at all.)",
		"(Here at ICE-E'S PEZZA, You're Family.)<br>* (... Is Going to Love it!)",
		"Does it hurt to be made of blood???",
		"I'm a normal person. I spend all my money on RENT and MYSTIC GEMs.",
		"Now, prepare thouself. For the STRONGEST puzzle of THOUST LIFE!",
		"GOD<br>* DAMN IT",
		"At times, you see it flickering. The light only you can see.",
		"Hey. Let me tell you a secret. Quiet people piss me off.",
		"See you again... Or not. Ha ha ha ha...",
		"I'll make you tea... And we can toast... to the end of the world!",
		"Artest thou one of my admirers, worm?",
		"I do not Wisheth to hear your MP3's! I would rather listen to the sweet song of Death!",
		"Ho ho ho! Let the Clown-Generated-Content begin!",
		"<span style=\"font-family: Comic Sans MS\">ah, sorry. i don't hang out with idiot babies. they compete with my sociological niche.</span>",
		"<span style=\"font-family: Comic Sans MS\">too late. i already \"befriended\" your mom last night.</span>",
		"Why'd you call the Hotline for Idiot Babies if you aren't an Idiot Baby?",
		"A MARVELLOUS FUN IS ABOUT TO BREAK FREE.",
		"Lightners Love Traffic They Look It Up All The Time",
		"Poor Noelle She Would Love Hitting All These Cars",
		"OK There's Nothing Wrong With Him He's Just Annoying",
		"HEY		EVERY	  !! IT'S ME!!!",
		"WOAH!! IF IT ISN'T A... LIGHT nER! HEY-HE Y HEY!!!",
		"HAEAHAEAHAEAHAEAH!!",
		"THAT'S RIGHT!! NOW'S YOUR CHANCE TO BE A [[BIG SHOT]]!!",
		"HEY!!! DIDN'T YOU EVER HEAR THE PHRASE, [Make Money, Not War]!",
		"You... you said I could trust you!! You said you were a GAMER!!!",
		"Fear not!! Your knight in glow in the dark armor is here!!",
		"Okay! ...? What do you mean, undefined!?",
		"Don't cry, chicken-nugget-man. All of us are idiots, too.",
		"You're not only kind, but a true gamer as well.",
		"I will turn over a new leaf from now on... And FIGHT! For the side... OF IGNORANCE!!!",
		"WE'RE NOT TELLING YOU TO BE STUPID!!!",
		"Chips Ahoyeth, Landlubbers!",
		"This world... I wish Dess could see this.",
		"I'd grow big angel wings, and fly as far as I can, gazing back at it all...The skyline shining like Holiday lights.",
		"WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT? WHAT?",
		"(Sort Of Regal Mostly Cruel Laughter)",
		"(Only a kiss from a beautiful gamer girl can save me now...)",
		"Now, Which One Of You Wants To Help Me Cover This World In Darkness!?",
		"Error: I Have No Idea What You're Talking About",
		"Fatal Exception \"Sweet\" In Oh Hell Yeah.EXE",
		"I'm Just A Computer LMAO I Don't Know Everything",
		"Do you know what they call a sleeping Susie? They would call her... A \"Snoozie!\"",
		"Books. God. Damn. Crazy about them.",
		"Screw it let's just go play Space Pinball in the computer lab",
		"I Have No Time For Such Frivolities (And Would Kick Your Ass)",
		"[[Designed BY The Classics You've Come To Expect! (C)1997]]",
		"It's still DARK... SO DARK!",
		"WOW!!! I'M SO [Proud] OF YOU, I COULD [Killed] YOU!",
		"[Heaven], are you WATCHING?",
		"WHAT! THE! [Fifty Percent Off]!?",
		"[Why] DID YOU DO THIS!? WHY!? [Y]!? [Yellow]!? [Gamma]!?",
		"Too late, already imagining you guys as idiot-scented candles.",
		"What? No, I'M not giving YOU a hug! That's what Ralsei's for!! He's like a portable teddy bear!",
		"(The mice found $20.)<br>* (You didn't get any.)",
		"THANKS TO YOUR [Total Jackass stunts] I HAVE [Becomed] NEO.",
		"(It was as if your very SOUL was glowing...)<br>NOT!!!",
		"Isn't this mix...schway?",
		"Does anyone want this milk I found?",
		"Lost eternally in an endless night...Is that your idea of paradise?",
		"(I can't help it, I'm a cutey guy.)",
		"(Rolling around at the speed of mouse...)",
		"(The cheese was destroyed in the heat of battle...) (Feels like you lost sight of what was important.)",
		"Sorry, I'm out of bagels.<br>* Don't you have 400!?<br>* I had 406.",
		"Split up? We'll solve this mystery fast! You? You can be the un-talking dog.",
		"Sounded like milk out there. Splat! Were you three osmosing without me!?",
		"Well, there is a man here.",
		"Well, there was not a man here.",
		"BUT IT WAS SUCH A GOOD YEAR.",
		"I now pronounce you... cookie and wife.",
		"Like night and day, the cake and the world revolve!",
		"This music, it's nice music.<br>* That's my favorite genre.",
		"Look!!! LOOK AT THIS!!!! GOD DAMN!!!!<br>* (It's several pixels that vaguely resemble a zoomed-in JPEG of a pepperoni pizza.)",
		"(Wait, maybe making her a lunchbox full of chalk is stupid...)",
		"[[Hyperlink blocked]].",
		"KRIS!!! YOU DID IT!! YOU [[Funky]] LITTLE [[Worm]]!",
		"DON'T FORGET TO [Like and Subscribe] FOR MORE [Hyperlink Blocked]!",
		"TOO MANY EXCESS VACATION DAYS?? TAKE A GOD DAMN VACATION STRAIGHT TO HELL",
		"TURNING DOWN A BELOVED [[Stranger]]... THAT'S NOT VERY [[Big Shot]] OF YOU, KRIS.",
		"CONGRULATIONS YOU ARE THE 100th VISITOR!!! CLICK HERE TO [Die]",
		"DEAL OR NO DEAL, THAT'S THE TV SHOW WHERE THE PEOPLE WHO DON'T TAKE THE DEAL<br>GET FILLED WITH BULLETS FIRED FROM THE HOST'S MOUTH!!!",
		"YUM YUM. DELICIS KROMER. DID YOU HAVE AN YMORE?",
		"YOU DON'T NEED [Friends]!! I CAN MAKE MY HANDS INTO PHONES!!!",
		"DO YOU WANNA BE A [Heart] ON A [Chain] YOUR WHOLE LIFE!?",
		"DIDN'T YOU KNOW [Neo] IS FAMOUS FOR ITS HIGH DEFENSE!?",
		"KRIS!!! I UNDERSTAND NOW!! THE GREATEST DEAL OF ALL!!! [Friendship]!!!",
		"K_K, are we players!?<br>* ...<br>* I'm a CD player.",
		"owowowmememeowmeowmemeowowmemeowowmeowmemeowmeow",
		"Happy new year 1997!",
		"This girl is so sweet... Let's give her free bullets!",
		"Poppup wants To Play With You In The Mystical Island Of Mysticisland",
		".....ASOBOH......?",
		"Yeah My Final Attack Like<br>* I Was Going To Put Like Memes In It And Stuff",
		"THEN THE WORLD<br>WAS COVERED<br>IN DARKNESS.",
		"... is this that nightmare? ... or was everything else a dream?",
		"YOU MAY FORGET ME, I MAY FORGET MYSELF, BUT I WILL REMEMBER YOUR KINDNESS.",
		"WHETHER 11 HOURS OR 11 YEARS, DELTARUNE WILL BE WAITING.",
		"Having fun?",
		"You're very interested in going nowhere, aren't you?",
		"Oh, don't make that sour face. I can see in the dark you know!",
		"Does anyone know what an e-mail is???",
		"MIKE, the BOARD, please!",
		"Special Thanks<br>Dark Fountain That Gives The World Form",
		"Fresh from the Juice, Fresh from the Juice! Make sure you don't get it on your shoese!",
		"I'll give you funny goop that gets stuck on the carpet! A lifetime supply!",
		"Umm, sure, just... Why do I have to be the horse...!?",
		"But what if? What if it became even darker? Darker than dark.",
		"Wow, what an <span style=\"color:#FF6B6B\">A</span><span style=\"color:#FFEA6B\">M</span><span style=\"color:#95FF6B\">A</span><span style=\"color:#6BFFC0\">Z</span><span style=\"color:#6BC0FF\">I</span><span style=\"color:#956BFF\">N</span><span style=\"color:#FF6BEA\">G</span> performance!!",
		"What the HECK is THAT THING!? Some kind of RAT!? Some kind of CREATURE!?",
		"Suddenly, a tempest.",
		"Kris, games are supposed to be fun. Don't let it feel like a job, alright?",
		"Ah, Kris. Stick around here long enough, and you'll learn... Freedom's just a thing for big shots.",
		"But, heh, now that the games are almost over... Makes you think, was it really all such a good idea?",
		"I GUESS YOU GREW UP. WELL, STOP THAT.",
		"(Dustin' makes me feel good...)",
		"... Gee whiz, you don't know the personality of your own trashcan?",
		"\"LIGHT nER! HAY-HA Y HAY!!!\"<br>* (... is what it felt like your glasses would say.)",
		"It's a lucky's world! Do or die!",
		"A lost and lost and lost girl.",
		"Ha! Quell your mouth, my dearest Bimbitoe! We're just hereth for the Snackse.",
		"All right, fine! FINE, I ADMIT IT! Maybe I AM a little GLOOBY sometimes!!",
		"CLAP AND CHEER, SMILE AND SCREAM! ENTERTAINMENT ON YOUR SCREEN!",
		"DON'T TOUCH THAT DIAL! THINGS ARE HEATING UP!",
		"HEAR THAT WHINE!? THAT'S YOUR CRT ASKING FOR A WALK!!",
		"Miss something!? The battle will be available on laserdisc!",
		"Dan called! He wants his maku back!!",
		"AREN'T YOU HAVING SO MUCH FUN?",
		"Come follow me into the dark<br>With your heart as the ark<br>Which shall shine you the way",
		"Don't forget,<br>I'm with you in the dark.",
		"Anyone, if you're there... thank you.",
		"How's it going? Ya winning, kids?",
		"It was the best of times, it was the blurst of times.",
		"I... I want to. I want to believe again. I want to believe... it can change!",
		"Susie's hope... Her naive hope... It's... infectious, isn't it, Kris?",
		"When the sun comes up again... I want tomorrow to be the same as yesterday.",
		"Pump the tunes! Pump the tunes!! Pump the tunes!!",
		"(Kris will sing swears.)",
		"HOW MUCH LONGER NOW...?<br>MY DELTARUNE.",
		"Oh, Holy Princess far above! If you would spare but a drop of your love...I promise I should never spill it, or mix it with powders to modify its flavor.",
		"Surely this legend shall make me a righteous hero. If it doesn't make me a righteous hero, then it really sucks.",
		"IF YOU DIDN'T READ IT HOW DO YOU KNOW WHAT IT SAID!?",
		"Mee-yike, that's right!",
		"I'll make you pay!! I've got connections!! I've got friends on the inside!!",
		"I swear, you people see PINK and YELLOW and think, oh, a FRIEND!!",
		"Being a friend doesn't make you them YOURS! Those teeth, they BITE!",
		"Maybe I was too modern, too relevant...",
		"Nice to meet ya. Some more. I'm still Mike.",
		"Mike is definitely...!?",
		"Am I still dreaming?",
		"Heheh, alright. And if it's a severed hand... I'll keep it as MY pet.",
		"LET ME KNOW IF I CAN EVER REPAY YOU... I LIVE IN A HOAL",
		"To be Susies' friend, is to be, the World's Enemy. Which, is sick. I respect, your Game, Kris.",
		"Now I'll get to sing rock-a-bye biiby to Tenna's cupboard all by myself...",
		"Oh Dear First You Don't Want To Swim In The Free Pool<br>* Now You Don't Want To Drink The Free Pool Water",
		"<span style=\"font-family: wingdings\"><big>THIS NEXT EXPERIMENT SEEMS VERY VERY INTERESTING</big></span>",
		"<span style=\"font-family: wingdings\"><big>THREE HEROES APPEARED TO BANISH THE ANGEL S HEAVEN</big></span>",
		"Thank you...",
		"An ending, huh... If I could choose... I guess... I wouldn't have an ending!",
		"It's just better if stuff just... goes on forever, right?",
		"Well ain't that somethin'. At this late hour, with the bells ringing out their justice. You choose eternity.",
		"So the story goes, so the story goes. But ain't every story better with a little twist?",
		"So... how do you think it all ends? No, how do you want it to end?",
		"There's no prophecy or legend 'bout anyone like that. It's just something I know is true.",
		"...GO BACK... YOUR TAKING... TOO LONG...",
		"WHAT THE HEACK WAS THAT PUMKIN THAT WAS SCAIRY!!!",
		"TONAIGHT, ON THE MOST HAUNTED OF NAIGHTS... I SHALL INFLICT YOU WITH MY GRAITEST CURSE...<BR>THE SAME THING I WAS USING THE WHOLE TIME",
		"Get a terrariam for your computer, and you can touch grass as you game.",
		"If you're a married from a girl, any Life's Hack, is a Wife's Hack.",
		"... Susie beat up an old man!?",
		"BUT LO, ON HOPES AND DREAMS THEY SEND.<br>THREE HEROES AT THE WORLD'S END.",
		"THE POINTY-HEADED ONE WILL SAY \"TOOTHPASTE\", AND THEN \"BOY.\"",
		"Want a free sample? Just $4.99 to try a bite of these clothes!!",
		"I'm a worm. I don't understand taxes and values.",
		"Yea i'm tha sicko that looks at all the milks to find the best expiration date",
		"Ah, you two don't look together! Can I interest you in some brand new Divorcing Shoes...?",
		"This is a dream that grows with love and care. Don't be afraid to dream!",
		"(Looks like this Gamer's Paradise has become a Gamer's Hell.)",
		"KID! I'M BUSY BECOMING [God]. GO PLAY [Minecrap] OR SOMETHING!",
		"It's like a spiral.",
		"ARE YOU THERE? ARE WE CONNECTED?",
		"YOU ACCEPT EVERYTHING THAT WILL HAPPEN FROM NOW ON.",
		"Guys I Think I Drank Too Much Of This Battery Acid (Ages 3 And Up)",
		"If humans are made of bones... Where does skeletons come from...?",
		"HOt and fresh chease, pepperonie, Just like in your Dream's...",
		"Poppup wants Do Taxes At 7:44 AM",
		"TAKE THIS DEAL AND YOU WILL [[Die]]!! IT'S THAT GOOD!!!",
		"What is it that I must say...? ... \"nya,\" was it?",
		"\"Throughout my career, some of my best ideas came from dreams.\"<br>* \"Take a rest here. If anyone asks -- you're writing!\"",
		"Lost...? Frightened...? Confused...?<br>* GOOD!! HA HA HA!!!",
		"When did you start being yourself?",
		"If only a true master of \"BREAD\" existed...",
		"We know nothing. We understand... nothing.",
		"O, the Pianosong, it plays on in my heart.<br>* Duh duh duh, doo doo doo, dee dee dah... and stuffs.",
		"THE CAGE, WITH HUMAN SOUL AND PARTS!",
		"THE GIRL, WITH HOPE CROSSED ON HER HEART.",
		"THE PRINCE, ALONE IN DEEPEST DARK...",
		"Hope, written in truth. Written somewhere... Written somewhere no one can erase!",
		"Haven't you heard of Hyperlink Blocked?",
		"Who will call the girl who snows?",
		"The weather always sticks together!",
		"It feels like a whirlwind.",
		"The story, it became so grand, so overwhelming, some say it swallowed up the author himself.",
		"ARRGH!! NO!! MY BUTT IS MY FACE!!",
		"PIIP PIIP, LET'S RIDE THE CAROUSEL GAME.",
		"HEARTS, DIAMONDS, I CAN DO ANYTHING!",
		"PLEASE, IT'S JUST A SIMPLE CHAOS.",
		"We're bad guys, so we only have BAD-byes!!!",
		"Lots of blood!<br>* Splooshing blood!<br>* Very gross and bad!",
		"Well well well... Look who it is.<br>* The Sweet Little Peas We Love To See.",
		"There's always room in town, for a couple of clowns!",
		"(I'm just a little ball, I don't want to discuss anything.)",
		"If you need someone to change your diaper, go ask the Cop's.",
		"Come, knaves...! Prepareth for battle with...!<br>* Whatever this is!!!",
		"AHHHHH HA HA HA HA HA HA HA HA!!!!<br>* Merry Christmas!",
		"Your machine sucks ass.<br> Is that OK?",
		"Well jingle my goshdarn bells! Looks like Krismas came early!",
		"It's my secret stash.<br>* A little snackeroo from me to you...",
		"Watch what happens when I cast a spell I don't know!",
		"Stop Everything<br>* Kris Get The Banana",
		"Potassium",
		"What The<br>* Who The Beep Said You Could Double Trucies",
		"I Will Only Say It One Time<br>* Infinitely<br>* Get Over Here Get Over Here Get Over Here Get Over Here Get Over Here",
		"(You ate the moss... together.)",
		"DO NOT SPEAK ILL OF THE ROYAL WATER BOTTLE!",
		"My son... is...<br>* A bouncy little pumpkin.",
		"Bye Bye Kingy Wingy<br>* By The Way Did You Want Anything From The Store",
		"I Shall Humiliate You At: A Simple Children's Diversion",
		"So Like<br>* You \"Guys\"<br>* Hey<br>* Are You Like<br>* ...<br>* Doing Anything Right Now",
		"It Means Tity",
		"(I Did Not Ask Him I Did Not Ask Him I Did Not Ask Him)",
		"I Love Tolerating You",
		"Very Cool Statues<br>* I Did Not Know You Had... Nipples",
		"Haha Yes Oooh So Good Looking Forward To That<br>* MMmmm Yum Yum Yum Yum Yum",
		"No!! I love ditches but I would never ditch you!!",
		"Yes!! And I saw it all!!<br>* Pants. Lint. Various Items.",
		"Ha ha!! I love getting nauseous with friends!!",
		"You can always rely on a friendly Me...<br>* To make you free!!!",
		"Let's go, blue person whose name I know!",
		"Go forth!! My Squeakie Duckie!!",
		"So thou hath beateneth The Crappeth out of Me.",
		"Well shivereth my timbereth, you little Bimbo!",
		"SHUTTETH YON UPPETH!",
		"Yes!! Don't worry, Noelle!! I'm stupid now!!",
		"Ah My Sweet Idiot Children<br>* You Are Just In Time To Witness My World Domination",
		"You Are Definitely Going To Kick: My Ass",
		"Oooooo Ouchie Mama",
		"Seems That You Failed To Notice<br>* The Giant Freaking Robot In The Middle Of My Palace",
		"With a power like that...<br>* Maybe you three can break your own strings.",
		"Ha Ha Just Kidding<br> I Totally Will Keep Monologuing As I Kick At: Your Face",
		"Bro Just Let Me Karate Chop You",
		"You wanna get into Politics? Heh.<br>* You better graduate from Diaper School first.",
		"Hey, got any way to deal with crushing, existential dread?<br>* Asking for a friend.",
		"Normally I'm terrified of mice, but it's OK because that one is wearing a wig.",
		"I'm Nubert. Everybody loves me.<br>* That's why I live in the trash.",
		"But when I put the receiver to my ear...<br>* There was nothing but garbage noise.",
		"I'm Lancer! Pull my tongue and I'll say several phrases!<br>* Such as \"ow,\" \"ouch,\" \"aaaah,\"",
		"Can't even cross the street without getting my ass kicked.",
		"Where there's a wee, there's a woo.",
		"Perish Under My Bosom Or Whatever",
		"So That Final Move Was Supposed To Be Cooler But The Internet Is Down",
		"Yeah Still Thinking About That Move HashtagFinalAttack",
		"Hey Chat Does Anyone Know What Happened To That Stuff",
		"Bro That's Weird But OK",
		"STOP HITTINGETH ME AND PLAYETH MY MINI-GAME, YOU ROGUES!!!",
		"The power of fluffy boys shines within you.",
		"The power of mean girls shines within you.",
		"See ya!<br> Smell ya!<br> Hear ya!",
		"DEALS SO GOOD I'LL [$!$$] MYSELF!",
		"WAIT KRIS LOOK!! HEAR THOSE [Balloons]??? YOU ARE [1000th Customer]!!.",
		"I USED TO BE NOTHING BUT THE E_MAIL GUY, NOW I'M THE [[It Burns! Ow! Stop! Help Me! It Burns!]] GUY!",
		"KRIS!!! DON'T BELIEVE [[Anything You See On TV!]]<br>* THE MAN'S A CRIMINAL, I TELL YOU!! A CRIMINAL!!",
		"[The Smooth Taste Of] NEO",
		"I'VE ALWAYS BEEN A MAN OF THE [PIPIS]. A REAL [PIPIS] PERSON!",
		"HERE I GO!!!! WATCH ME FLY, [MAMA]!!!!",
		"That golden statue... Could it be...<br> The illusory nipple technique!?",
		"The bluebird of crappiness.<br> Fly high, bluebird. Fly high.",
		"Wanna share my soda? We'll both get sick that way... Hee hee.",
		"All proceeds go to kicking your ass.",
		"Just two friends, chillin' out in the closet, like normal.<br>* Touchin'... brooms and stuff.",
		"(After all, a dream is just a dream, right...?)",
		"A rousing battle! Mike! Give them a free tube yogurt!",
		"Ralsei plush! Fill him with liquid, throw him against the wall!",
		"Stop advertising me! I'm dying!",
		"This is getting awkward kid just push him",
		"Uh oh! Weed alert!",
		"Sigh... Can't a guy have just one bonus zone to himself...?",
		"H-huh?! Make smoochies, not smoothies...",
		"LOOK. GUYSE. I'M LOSTE. I DIDN'T MEAN TO MAKE A SHOP.",
		"Yea, yea, Okaye, we get it, We Good, let's go.<br>* Cue Rainbowe.",
		"Oh, you WILL!?!? Oh, you THRILL!?",
		"Mike!! The lights!! The sounds!! The whatzits!! The doo-zits!!<br>* Turn 'em all on!!",
		"Hey folks, looks like the censors ARE gonna kill me!",
		"Mike! Tear down the board! Tear down the set!<br>* Tear down my house!! Tear down my kids!!",
		"And now a WORM from our sponsors!!!",
		"I'm not broken! I don't have burn-in! I'm... fun!!!",
		"AhhHHHH, that was SO... Normal!",
		"So I haveth a Laser Pointere.",
		"Sorrye, I just wanderedeth in here. Are those two... Single?",
		"HAHA!! I LOVE WATCHING TV!!",
		"They're sayingeth, I'm Hotte.",
		"Okaye. Thou just jealous causeth thoun Throuple doth suck.",
		"It was just Us. Alone. Yon losers. Lo, Medieval L, on mine forehead.",
		"Okaye. Okaye. I see. I see.<br>* Your a little bit Fired, byst the way...",
		"I really didn't like that guy that much!<br>* He was hot but really weird!",
		"Let's stick Ralsei in the machine and see how much money he costs.",
		"Oh no! So many Tennas balls! Who is responsible for this madness!?",
		"Look how small and disgusting his nose is!!! Yuck!!!",
		"Kill him!!! Kill him now!!!",
		"What the $*!? are you doing!? Kill him!!!!!",
		"PHEW!!! YOU GUYS SAVED TV!!! YOU HAVE WON!!!",
		"I'm still MARVELOUS! I'm still MYSTERIOUS!",
		"Just ME... alone. Glooby... against the whole world...",
		"Buble",
		"Now where the heck is my debit card?",
		"No one will shed a tear for him. Inside, he was probably stone already.",
		"... VERY WELL... IF YOU COME CLOASER TO THIS PLACE...<br>* ... THEN YOU MAY FIND...<br>* ... THE DARK...<br>* ... HAS COME TO YOU!!!",
		"I WAS BULLYED, AND HAITED BY THE OTHERS, FROAM MY LARGE AND UGLY BODDY.",
		"ACTUALLY IT'S TOO SCAIRY",
		"It's just... sometimes, knowing things...<br>* It hurts.",
		"And if anyone's going to hurt...<br>* Let it... just be me, okay?",
		"Everything's OK, Kris. Look, I...<br>* I'm smiling!",
		"Ahh.<br>* Church flavor.",
		"Proceed",
		"Get. Your hands. Off. That guitar.",
		"As you know, <span style=\"color:red;\">YOU</span> are welcome here any time.",
		"You are... the Dragon.",
		"Ain't no better story than one told with sparkling eyes.",
		"Please find someone to adopt me",
		"Freak freak freak family<br>* Freak family (your family)",
		"Kris Do You Have Any Games On Your Phone",
		"(Hath she NOT noticed her lamp's Bouncinest Bootye...?)",
		"French fry, (oo), on the ground and soggy.<br>* Am I gonna eat it? (No!) I ain't some, uh, doggy.",
		"(You hear nary a bone... No rattle, nor trousle, nor xylophone tickle.)",
		"Gee, haha, what a stupid looking lamp, folks! Like the lamp itself is stupid!<br>* (...)<br>* It also has a small ass.",
		"(You are filled with the power of not actually reading the text.)",
		"THEY'LL HEAR THE RING OF HEAVEN'S CALL.",
		"THEY'LL SEE THE TAIL OF HELL TAKE CRAWL.",
		"THE KNIGHT WHICH MAKES WITH BLACKENED KNIFE.<br> SHALL DUEL WITH HEROES STRIFE BY STRIFE.",
		"THE QUEEN'S CHARIOT CANNOT BE STOPPED.",
		"THE LORD OF SCREENS CLEAVED RED BY BLADE.",
		"THE FLOWER MAN, TRAPPED IN ASYLUM.",
		"JOCKINGTON GROWS THE BEARD.",
		"AND THEN. WHEN ALL HOPE IS LOST FOR THE TALE<br> THE FINAL TRAGEDY UNVEILS.",
		"AND LAST, WAS THE GIRL.<br> AT LAST, WAS THE GIRL.",
		"Oh, heavens to yikes! Where's my Dragon Blazers barf bag!?",
		"Shelter? I hardly know 'er! HAHAHAHA!!! ... what?",
		"HOT DAMN!!! LITTLE BUDDY!!! LOOK!! LOOK NOW!!!<br>* She just edited a meme... to be ABOUT US!!!",
		"YOU WERE USED UP.",
		"What will happen to our HEROES...<br> When they REALIZE this show is NEVER gonna end!?",
		"You don't even have to come in! Stand outside and watch me through the window!<br>* I won't tell anyone!! The police will never know!! Promise!! Hahaha!!",
		"Someone out there wants you. Promise.",
		"Choose The World... That Makes You Happy",
		"Don't drag me into this I'm just looking (at milk)",
		"Keep your chin up, Kris! This whole house is your friend!",
		"MARVELOUS!!! Mike, rebuild the set!! Rebuild my kids!!",
		"Wh-what are you doing!? I just had this suit DE-AXED!!!",
		"... Though, I do like goin' the wrong way.<br>* You get better ideas that way.",
		"MIKE... MIKE, IF YOU'RE STILL HERE... BAN EVERYONE FROM THE GIFT SHOP!",
		"Step one.<br>* I thrash you.<br>* Step two.<br>* You lose!",
		"The power of reoccurring bake sales shines within you.",
		"Last one there is a fresh and fragrant egg!!",
		"You Get Me Kris<br>* You Do Not Do Crazy Things Like \"Have Opinions\"",
		"I Just Want To Make Everyone Smile<br>* And If I Become An Evil Villain To Accomplish That<br>* Is That Bad?",
		"Keep Going I Am Right Behind You<br>* Procedurally Lowering The Volume Of My Voice",
		"I just wonder what... being \"Ralsei-like\" even is...?",
		"Uh... seeing everything small, makes me feel like, um...<br>* If I was Susiezilla or something, I could wreck the whole city.",
		"Okay I Believe I've Made My Point I'm Going To Procedurally Loop My Dialogue Now",
		"If only I could dream like this every day...",
		"Maybe...<br>* It... doesn't have to be a dream. Y'know?",
		"(It's hard to put into words, but for some reason, seeing Susie next to you...)<br>* (... You felt like, whatever you were, for just right now, it might be okay.)",
		"What is this feeling? ... Hope? Hahaha! Whatever it is, it's quite funny!",
		"Around here, you learn to find ways to pass the time...<br>* ... or go mad like everyone else.",
		"You're a Lightner. Don't take your life, well, lightly!",
		"Your design sucked so we blew it up.",
		"Kris!?!? WAS THAT A [BIG SHOT] JUST NOW!?",
		"No one can choose who they are in this world.",
		"It was as if your very SOUL was glowing...",
		"Spamton flashes an award-losing smile.",
		"Where my boys at now. I don't know. It's been 24 hours. I might as well be dead.",
		"... I don't need slop... I don't need slop... I don't...",
		"Remember to obby for pink coins. Then it's catgirl time.",
		"O French fry on the floor... it's you that I adore...<br>* Greasy and salty and lots lots... more?",
		"Hahahahaflowershahahaha.",
		"Can you get me a hot gamer boyfriend.",
		"Can you get me a hot gamer girlfriend.",
		"It's... just... it's going to ruin... It's going to ruin the economy!!!",
		"Sorry to keep you waiting!",
		"Two eggs over Very Hard. Two eggs over Expert Mode. Two eggs over... ha ha ha... \"LUNATIC\"...",
		"Human beings don't, um... generate... juice.",
		"Hee hee! What's going on!? Is the whole world revolving!?",
		"(Watch for falling peaches!) <br>* (... and don't call them rocks. Those aren't plant-themed.)",
		"Listen, have you had ears before? Cute and fluffy ears? <br>* ... you should try it.",
		"Haha! I knew it! You're like an open book! And I definitely read books!",
		"Once again, my analysis has proven fruitful, or even vegetable-ful!",
		"Blue, blue! Blue, blue! We are knife friends, and blue!",
		"Anyway, really gotta get my punishment now! Y'all have a great day! Toodle-y-kay-yay!",
		"I'm not a strong boy. Don't treat me like one of your items.",
		"Also, I replaced my sword with a big stick of butter.<br>* And I been liiiicking it.",
		"\"Playin' Smash\" ain't ever right.",
		"Do you have any smoked herbs? Like, oregano?",
		"Here... real \"justice\" is playin' with gun's.",
		"Hey, smile again. I know no matter what... You guys are gonna save the world.",
		"Got it, Princess?",
		"I think it's good that you're \"cringe\".",
		"Uuu, can I have compound eyes!? Like human, like human!",
		"I want to eat sand on the beach with you, mew!",
		"Since the beginning, we were love...",
		"Imagine that... a branch where we didn't have to fight. We could even call it a \"pacifist root\".",
		"That's right. No matter what you are... We're all gonna beat you with hammers for your crimes.",
		"But even if it ends, love... will always continue.",
		"Thank you for watching our dream.",
		"It's time this capricious reverie came to an end.",
		"Way up high in the sky<br>With the sun in your eyes<br>Ain't it nice?",
		"A FLOWER TORN IN HALF! I WONDER WHO TOOK IT... THE PHOTO, I MEAN.",
		"(... can I... look like this... can I... dream like this...)",
		"Everything about him is an illusion... but, with hope, can he make it real!?",
		"Spring may change to Fall, but my Season 2 will never falter!",
		"Even though we never interacted, our spirit unites us, hyuk!",
		"Uhh, hey. Nice to meet ya. It's me. Motormouth Plooby.",
		"(The size of Mike's ass, seems really variable lately.)",
		"Ha ha, you eat food when you're hungry",
		"Blue, blue, blue-be-doo. Was your love true?",
		"You're MIKE!!! PLUEY is the name of the MINIGAME!!!",
		"Look! I have made DELECKERTIBLE SAUERDOUGH. And no one has ever destroyed it. YIPPEE!",
		"Your dad's my best friend!",
		"UUAAAAAAGHHH!!! THAT WAS MY ULTIMATE MOVE!!! AAAAAAAAAAGHHH!!!",
		"Right, of course, I'm also human. That's why I look and feel like a flower.",
		"My magic, my Omega, can you follow!?",
		"All according toAll according to plant!",
		"Here I come, San Frandisco!",
		"I'm tired. Can I just beat someone up?",
		"I THOUGHT I heard someone misusing the BATTAT motif!!",
		"Someone has to take care of the flowers.",
		"That's right, go outside. It's beautiful.",
		"The sunset... will it ever be this beautiful again?",
		"Treasure this world, won't you?",
		"The air swirls in rosy chaos.",
		"Flowers blooms in your heart!",
		"Mostlys!",
		"(Swishes my big fluffy $$$$-ing tail)",
		"By the way, don't worry. I'm a gentleman, so I only did CPR's on your cheek.",
		"B-but what will the VIEWERS think! Oh, Mike-kun...",
		"A FRIEND... is someone... you LIKE... to SEE. An ENEMY is someone you STAB with a KNIFE!!",
		"... I'm going to make friends here. I know it. Lots and lots of friends...",
		"W-was I brave!? You'll say I was brave, right...?",
		"We are mere messengers. Messengers of love.",
		"Birthed from dark, baptized with name and ego. And until the sun rises, I too shall dance my part...",
		"To which you seek to put a face... You may find no more than a butterfly.",
		"Ho ho ho! I smell with my nose, a wonderful clothes!",
		"Don't you wanna do something crazy?",
		"Why don't we do... \"Something crazy?\"",
		"I thought it was one of the best days ever... But, I guess it's still getting better.",
		"Holy cheese and crackers...",
		"It's just a little poison. It's fine. It's within government limits.",
		"It's not magic, is it? No, not something like this.",
		"I was hoping being human was about playing since I always wanted to play a game.",
		"Hey, don't talk to me. This is my big fluffy $$$$ing shrub.",
		"Cutie Mew Mew Magic で変身しちゃいましょう!",
		"Heh, how did you like my jarona!?",
		"Seems like you still... don't get it! <br>* Nothing is stronger than... a... Flower's... dream...!",
		"It was me!! I killed the handkerchiefs with blood!!",
		"Hum, is that all you can do? After all, humans are actually a little boring!",
		"Who revolves - the world, or I?",
		"This is a comedy, not a tragedy. Get up, you two.",
		"And each of you... Are you not here because of love?",
		"Then go forth... with love in your steps!",
		"I was wrong. The dream never happened.",
		"Kris... Thanks for walking me home.",
		"Hey, y'all. Kind of a DIY situation in here. Just gotta find a way to blow myself up.",
		"Dude, don't be an anti-smeller. It's FREE sniffs.",
		"I was almost enlightened until you stepped around like Lalalala",
		"I'm gonna eat so many cowboy-appropriate meals.",
		"Now go and don't come back until your enlightened... binch",
		"Sm... smokin' herbs!? That's illegal, son!!",
		"Justice does turn a blind eye to parsley...",
		"The shape of love may change. It may be different for each being. <br>But as long as that shape contains you... all you can do is step forward... and let it guide you.",
		"I'm just loopy for these circles of fun! Value, value, value!",
		"Oh, I knew I was a hot-snack lovin' criminell...",
		"Tell me, was everything always this beautiful?",
		"... then, what's my name? I suppose... it depends on the color of the sunset.",
		"Aha, such fine taste! Or bad taste, if that was sarcasm!",
		"And if I win, I will use all the powers vested in me... To promote. The love of these two beautiful girls.",
		"It like, sucks, if your girlfriend, like, died, but...<br>* Her name is like, making me hungry?",
		"Pretty soon, the sun will come out, and it'll be smiling too.",
		"Wow, you can throw knives? How resplended...",
		"Just leaf it to me!",
		"Kris Darling Honey Not Now Mommy Is Dunking The Court",
		"Okay I'll Just Continue Drinking My 1000% Child Safe Acid",
		"Feels just like old trees. I mean old times.",
		"Oh, IT'S WORSE! I gotta be punished eternal-style now...",
		"Where's PLUEY!? I wanna see my lil' PLUEY!!!",
		"Mike to meet ya. Uhh... <br>* I'm Plue'd to make your acquaintance.",
		"Of course, he pays us in Flowery Dollars...<br>* ... that's perfect! We can buy more bromides!",
		"If you want to \"beleave\" things can change... Prove it on your side, sprinkles.",
		"Nyon!",
		"I think, everything. Was wrong. With what you just said.",
		"(Kris, be careful not to turn off RALSEIs in the thingy)",
		"Heh, it's my Jarona!",
		"Nothing changed.",
		"Nothing changed. <br>* Because a Noelle<br>* Is just a Noelle.",
		"Maybe in another life, we could have... been friends...",
		"... man, we could've been friends way before. Isn't that stupid...?",
	];
	const rdmQuote = quotes[Math.floor(Math.random() * quotes.length)];
	document.getElementById("randomQuote").innerHTML = `* ${rdmQuote}`;
});
