document.addEventListener('DOMContentLoaded', () => {
	'use strict';
	const characters = [
		'susie.png',
		'ralsei.png',
		'kris.png',
		'originalstarwalker.png',
		'lancer.png',
		'rudinn.png',
		'hathy.png',
		'clover.png',
		'spamton.png',
		'jevil.png',
		'virovirokun.png',
		'berdly.png',
		'kk.png',
		'tenna.png',
		'queen.png',
		'noelle.png',
		'poppup.png',
		'ambyulance.png',
		'king.png',
		'sweet.png',
		'capn.png',
		'pippins.png',
		'sneo.png',
		'gerson.png',
		'gerson2.png',
		'mizzle.png',
		'guei.png',
		'bibliox.png',
		'organikk.png',
		'wicabel.png',
		'shadowguy.png',
		'zapper.png',
		'shuttah.png',
		'jackenstein.png',
		'smallmike.png',
		'catmike.png',
		'cowboymike.png',
		'realmike.png',
		'milk.png',
		'winglade.png',
		'ralsei2.png',
		'missmizzle.png',
		'plugboy.png',
		'elnina.png',
		'lanino.png',
		'cround.png',
		'pippinsgreen.png',
		'hacker.png',
		'ramb.png',
		'roaringknight.png',
		'mantle.png',
		'swatchling.png',
		'nubert.png',
		'tasque.png',
		'tasquemanager.png',
		'rabbick.png',
		'rouxlskaard.png',
		'cuptain.png',
		'ponman.png',
		'balthizard.png',
		'maus.png',
		'mauswheel.png',
		'werewire.png',
		'electro_dasher.png',
		'jigsawry.png',
		'rudinn_ranger.png',
		'mysteryman.png',
		'werewerewire.png',
		'bloxer.png',
		'head_hathy.png',
		'titanspawn.png',
		'toriel.png',
		'soundofjustice.png',
		'ribbick.png',
		'asgore.png',
		'pink.png',
		'flowery.png',
		'yellow.png',
		'aqua.png',
		'orange.png',
		'green.png',
		'blue.png',
		'seth.png',
		'kawkaw.png',
		'pinkghost.png',
		'shi.png',
		'floradinn.png',
		'netskie.png',
		'shinobeetle.png',
		'terakota.png',
		'leafling.png',
		'sheary.png',
		'watercooler.png'
	];
	const image = characters[Math.floor(Math.random() * characters.length)];
	const toChange = document.getElementById('randomImage');
	toChange.src = `/assets/characters/${image}`;

	if (image === 'tenna.png' || image === 'sneo.png') {
		toChange.style.marginRight = '-25px';
	} else if (image === 'jackenstein.png' || image === 'clover.png') {
		toChange.style.marginRight = '-25px';
	} else if (image === 'tenna.png' || image === 'sneo.png') {
		toChange.style.marginLeft = '0';
	}
});
