name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Pull repository on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/public/smf
            git pull
            find /home/public/smf -type d -not -path "*/.git/*" -exec chmod 777 {} \;
            find /home/public/smf -type f -not -path "*/.git/*" -exec chmod 666 {} \;
